pipeline {
	agent {
		node {
			label app-worker
		}
	}
	stages {
		stage('Sonarqube') {
		    environment {
		        scannerHome = tool 'SonarQubeScanner'
		    }
		    steps {
		        withSonarQubeEnv('sonarqube') {
		            sh "${scannerHome}/bin/sonar-scanner"
		        }
		        timeout(time: 10, unit: 'MINUTES') {
		            waitForQualityGate abortPipeline: true
		        }
		    }
		}
		stage('Gather version info'){
			steps {
				//identify version info from git tag
			    script {
                  def tagCommand = 'git describe --exact-match --tags HEAD'
                  def retCode = sh(script: tagCommand, returnStatus: true)
                  def tagExists = (retCode == 0)
        
                  if (tagExists) {
                      env.TAG = sh(script: tagCommand, returnStdout: true).trim()
                      sh("echo ${env.TAG} >> VERSION")
                  } else {
                      def dirtyTag = sh(script: 'git describe --tags --always HEAD', returnStdout: true).trim()
                      sh("echo ${dirtyTag}-SNAPSHOT >> VERSION")
                	}
              	}
				stash includes: 'VERSION', name: 'version'
			}
		}
		stage('Multi-platform build'){
			parallel {
				stage ('Windows') {
					agent {
						node {
							label win-builder
						}
					}								
					stages {
						stage('Build') {
							steps {
								checkout scm
								unstash version
								// we assume the build scripts
								// use VERSION file to identify
								// version of app
								bat 'conan build app/'
								bat 'conan test app/'
								stash includes: 'build/app/*', name: 'win-build'

							}
						}
						stage('Package') {
							steps {
								unstash 'version'
								unstash 'win-build'
								// a python script that calls
								// reads version from the VERSION file
								// and creates platform specific package
								bat 'python create-package.py'
								stash includes: 'package/*', name: 'win-pkg'
							}
						}
						stage('Sign') {
							steps {
								unstash: 'win-pkg'
								// use a wrapper script for uploading
								// files to signing server
								bat 'python sign-app.py win-pkg/'
								stash includes: 'signed-win-pkg/*', name: 'signed-win-pkg'
							}
						}
					}
				}

				stage ('MacOSX') {
					agent {
						node {
							label macosx-builder
						}
					}								
					stages {
						stage('Build') {
							steps {
								checkout scm
								unstash version
								// we assume the build scripts
								// use VERSION file to identify
								// version of app
								sh 'conan build app/'
								sh 'conan test app/'
								stash includes: 'build/app/*', name: 'osx-build'

							}
						}
						stage('Package') {
							steps {
								unstash 'version'
								unstash 'osx-build'
								// a python script that calls
								// reads version from the VERSION file
								// and creates platform specific package
								sh 'python create-package.py'
								stash includes: 'package/*', name: 'osx-pkg'
							}
						}
						stage('Sign & Notarize') {
							steps {
								unstash: 'osx-pkg'
								// use a wrapper script for uploading
								// files to signing server and notarize
								// the app
								sh 'python sign-app.py osx-pkg/'
								stash includes: 'signed-osx-pkg/*', name: 'signed-osx-pkg'
							}
						}
					}
				}
			}
		}
		stage('upload-to-artifactory'){
			steps {
				unstash 'signed-win-pkg'
				unstash 'signed-osx-pkg'
			rtUpload (
                    serverId: ARTIFACTORY_ID,
                    specPath: '/path/signed-win-pkg'
                )

			rtUpload (
                    serverId: ARTIFACTORY_ID,
                    specPath: '/path/signed-osx-pkg'
                )
			}
		}
		stage('ansible-qa'){
			steps {
				ansiblePlaybook(credentialsId: 'ansible_private_key', inventory: 'inventories/qa/hosts', playbook: 'app.yml')
			}
		}
		stage('Functional Testing'){
			steps {...}
		}
		stage('Publish'){
			steps {...}
		}
	}
}